import { ScoreboardTheme } from '../types';

export const retroTheme: ScoreboardTheme = {
    id: 'retro',
    name: 'Retro',
    description: '',
    colors: {
        background: '#eae1d3',
        backgroundSecondary: 'transparent',
        window: 'transparent',
        text: '#000000',
        textSecondary: '#000000',
        countryName: '#000000',
        countryNameBg: 'transparent',
        pointsOverall: '#000000',
        pointsOverallBg: 'transparent',
        pointsHighlightBg: '#000000',
        pointsHighlightText: '#ffffff',
        pointsGained: '#ffffff',
        pointsGainedBg: '#ff0000',
        border: '#000000',
        accent: '#000000',
        first: '#000000',
        second: '#000000',
        third: '#000000',
        gotPoints: '#000000',
        imagePlaceholderBg: 'rgba(0, 0, 0, 0.1)',
        imagePlaceholderText: 'rgba(0, 0, 0, 0.25)',
    },
    typography: {
        fontPrimary: "'Abril Display', Georgia, serif",
        fontCountry: "'Abril Display', Georgia, serif",
        fontPoints: "'Abril Display', Georgia, serif",
        fontVoterCountry: "'Above The Beyond Script', cursive",
        fontVoterLabel: "'Abril Display', Georgia, serif",
        fontPointsBubble: "'Abril Fatface', Georgia, serif",
        countryNameSize: '1.25rem',
        pointsSize: '1.75rem',
        voterCountrySize: '3rem',
        voterLabelSize: '2.125rem',
        pointsBubbleSize: '0.875rem',
    },
    spacing: {
        itemGap: '8px',
        columnGap: '20%',
        padding: '20px',
        borderRadius: '0px',
        itemHeight: 'auto',
    },
    effects: {
        glow: false,
        glowColor: 'transparent',
        shadow: 'none',
        windowShadow: 'none',
        itemHover: false,
    },
    assets: {},
};