import { ScoreboardTheme } from '../types';

export const win98Theme: ScoreboardTheme = {
    id: 'win98',
    name: 'Windows 98',
    description: '',
    colors: {
        background: '#030518',
        backgroundSecondary: '#030518d3',
        window: '#ffffff',
        text: '#000000',
        textSecondary: '#ffffff',
        countryName: '#ffffff',
        countryNameBg: '#027F81',
        pointsOverall: '#000000',
        pointsOverallBg: '#D7D3CA',
        pointsHighlightBg: '#FFC031',
        pointsHighlightText: '#000000',
        pointsGained: 'blue',
        pointsGainedBg: undefined,
        border: '#868686',
        accent: '#e1d5ec',
        first: '#FFC031',
        second: '#FFC031',
        third: '#FFC031',
        gotPoints: '#FFC031',
    },
    typography: {
        fontPrimary: "'Roboto', sans-serif",
        fontCountry: "'pix Chicago', monospace",
        fontPoints: "Arial, sans-serif",
        countryNameSize: '0.75rem',
        pointsSize: '1.5rem',
    },
    spacing: {
        itemGap: '10px',
        columnGap: '20px',
        padding: '10px',
        borderRadius: '8px',
        itemHeight: 'auto',
    },
    effects: {
        glow: true,
        glowColor: '#e1d5ec',
        shadow: '0 0 15px #e1d5ec',
        windowShadow: 'none',
        itemHover: false,
    },
    assets: {
        backgroundImage: '/background.png',
        windowFrame: '/background_98.png',
        taskbar: '/taskbar.png',
    },
};